#!/bin/bash

FRONTEND_DIR="dist/frontend"

build_if_necessary () {
  if [ ! -d "$FRONTEND_DIR/build" ]; then
    cd "$FRONTEND_DIR"
    npm run build
  else
    echo "No build necessary"
  fi
}

install_dependencies_and_build () {
  cd frontend 
  npm install

  npm run build
}

fetch_logic () {
  if [ ! -d dist ]; then
    mkdir dist
  fi

  cd dist
  git clone https://github.com/overhead525/iotex-dashboard-frontend.git frontend

  install_dependencies_and_build
}

pull_logic () {
  cd dist
  git pull

  install_dependencies_and_build
}

if [ -d "$FRONTEND_DIR" ]; then
  echo "directory exists"
  cd "$(dirname "$0")"

  UPSTREAM=${1:-'@{u}'}
  LOCAL=$(git rev-parse @)
  REMOTE=$(git rev-parse "$UPSTREAM")
  BASE=$(git merge-base @ "$UPSTREAM")

  if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
    build_if_necessary
  elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
    pull_logic
  fi
else
  echo "directory does not exist. creating it now.."

  fetch_logic
fi
